#!/bin/bash

#PBS -N coordinate_descent
#PBS -A WYOM0202
#PBS -j oe
#PBS -k eod
#PBS -q develop
#PBS -l select=1:ncpus=5:mem=20GB
#PBS -l walltime=06:00:00
#PBS -o coordinate_descent.log

## Setup temporary directory
export TMPDIR=/glade/derecho/scratch/lschneider/tmp
mkdir -p "$TMPDIR"

## Load required environment modules
ml conda
conda activate r-4.3

## Execute job
Rscript coordinate_descent.R
