#!/bin/bash

#PBS -N coordinate_descent
#PBS -A WYOM0202
#PBS -j oe
#PBS -k eod
#PBS -q main
#PBS -l select=1:ncpus=8:mem=32GB
#PBS -l walltime=12:00:00
#PBS -l job_priority=regular
#PBS -o coordinate_descent.log

## Setup temporary directory
export TMPDIR=/glade/derecho/scratch/lschneider/tmp
mkdir -p "$TMPDIR"

## Load required environment modules
ml conda
conda activate r-4.3

## Execute job
Rscript coordinate_descent_pure_numeric.R
