#!/bin/bash

#PBS -N competitors
#PBS -A WYOM0202
#PBS -j oe
#PBS -k eod
#PBS -q develop
#PBS -l select=1:ncpus=128:mem=256GB
#PBS -l walltime=06:00:00
#PBS -l job_priority=regular
#PBS -o competitors/workers_dev.log

## Set temp to scratch
export TMPDIR=/glade/derecho/scratch/${USER}/tmp && mkdir -p ${TMPDIR}

## Load required environment modules
ml conda mkl openmpi
conda activate mbo_config

pbsdsh -- /glade/u/home/marcbecker/mbo_config/hyperqueue/target/release/hq worker start --manager pbs --cpus 128 --idle-timeout 5m


